

### The config for what orgs/repos/branches to allow access to
### push to my AWS Account. Blocks should be in the form of:

# Organization:  # Dict - Org name
#   - Repository # List - Repo's to allow access to

### Can technically use wild cards (*), but it opens up security risks



# "Organization" is my personal account:
Cameronsplaze:
  # Repositories that can deploy to AWS:
  - AWS-ContainerManager
